dns_a_records:
  backup: 192.168.42.5 
  cf: 1.1.1.1

corp_nets:
  - 192.168.42.0/23
  - 127.0.0.0/8
  - 172.17.0.0/16

dns:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

mysql_primary: "{{ groups['db_servers'][0] }}"
mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_primary) | first | default(mysql_primary) }}" 

mysql_host: "{{ hostvars[groups['db_servers'][0]]['ansible_default_ipv4']['address'] }}"
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636264386265636639316537333262373463306636393330376638623037656264306466306263
          3331613061653435363639353138313037636334623361330a313738323830333265643837643730
          37386231666234393636333965633166626236663164383034346232343864303764396466316263
          3963336565613763610a616462613033656666653233363538643937613532353630346231343731
          3935



mydomain: batice.ttu



mysql_exporter_username: exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35306335343939303466373437336437616239346232616531656564326331316338616630643930
          3466303737313161336539383139313734303863643834370a316264656339323865383264653766
          36346161623461633336343039393831376139626630356333303330323335326239323664376436
          3732313361626136320a316436636262356134373431383033373234393830663639303565393636
          6262


grafana_user: mjeyhun
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63363135303330616634303730653561623238363438366134393565636138313338383035373638
          3365393362383264323532663735653135386330336537610a656666663235383064646562383564
          35386463306561343362303138316437323661343939323265626234623066383134613930353631
          3564636436633335610a306336363164653066656436646331313061353630303133656461653331
          3033


backup_server_ip: 192.168.42.5
backup_server_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAtnpnME3TsMyvcJyiYawMBod33jkDcFG9Pb1rlxDiXX"


backup_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62393066323736393164633635653763613764323261633663303862323463646663623436363437
          3937343766666466643033623937616139306338353761350a633466363430356464386661623432
          33633033303839613438356662376331656433396361653962623238663032303638626433326134
          6234613334643361340a396261653432376165303566646230356330323733396263626363383235
          3236

replication_username: replication

replication_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61303538623439353364366464656562323162393065303531303462636137373837663935366564
          6162323264666263326238316635306562653135333737640a373862393532386631363366346263
          62373836316464353964306463656463326437386431366635613335623761646664636537306537
          6564306264666166310a346466326437656432336639643831343866633861323766623431316565
          3334

node_id: "{{ (ansible_port / 100) | int }}"

grafana_port: 3001
agama_port: 8001

agama_container_count: 2


keepalivedpass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37383931323831346561633135316335343035346232643836636362316664616338643636636666
          3163393939666535383539663837633661656637653135320a383536613536643066376334653933
          34306638326437383335666132333332343533383935333066396137383862333635666532323631
          3737383638353439330a613263376638663862373337656164616264393065626163633535633939
          6662

haproxy_stats: 8404
haproxy_port: 88

prometheus_exporters:
  haproxy:
    port: 9188

transfer_key_name: "transfer.key"
tranfer_key_algorithm: "hmac-sha256"
dns_transfer_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34333035343932303231333266383333303164303238613337623533343364316662326439656563
          3939633566653365656262626135313535313330383533300a353131333735663263613031363466
          61323763656461323032613563616131396131303733383535303263643965393734353530613239
          6132383230346363340a383861393031316263613236303830333130613561303031333637616532
          33356631656237643130316338386235623965643737663764316564613936653130646533383136
          3033653861663461623562663038643530313934333631366538


update_key_name: "nsupdate.key"
update_key_algorithm: "hmac-sha256"
dns_update_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39653735326232323663306430323435373934316536303732356231313134653234663065636165
          3732613931633432373061666361623039333134373266620a323066613530313861366462376637
          31316637643032633438336234353166306362363764633939376433653439313666323739396232
          3661353164353262610a393238376661336132356236363364613166356438666332383333356634
          30373630373139306633633632313663393433373164323633623065643530653536386233666638
          6535613962613163643036636534353835306239636532653338



grafana_records:
  grafana: "{{ groups['grafana_servers'][0] }}"

loki_records:
  loki: "{{ groups['loki_servers'][0] }}"

prometheus_records:
  prometheus: "{{ groups['prometheus_servers'][0] }}"

nameserver_records:
  ns-1: "{{ groups['dns_secondary'][0] }}"
  ns-2: "{{ groups['dns_secondary'][1] }}"
  ns-3: "{{ groups['dns_primary'][0] }}"

web_servers_records:
  www-1: "{{ groups['web_servers'][0] }}"
  www-2: "{{ groups['web_servers'][1] }}"

haproxy_records:
  lb-1: "{{ groups['haproxy'][0] }}"
  lb-2: "{{ groups['haproxy'][1] }}"

db_records:
  db-1: "{{ groups['db_servers'][0] }}"
  db-2: "{{ groups['db_servers'][1] }}"
