mysql_host: 192.168.43.27
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636264386265636639316537333262373463306636393330376638623037656264306466306263
          3331613061653435363639353138313037636334623361330a313738323830333265643837643730
          37386231666234393636333965633166626236663164383034346232343864303764396466316263
          3963336565613763610a616462613033656666653233363538643937613532353630346231343731
          3935
