corp_nets:
  - 192.168.42.0/23
  - 127.0.0.0/8
  - 172.17.0.0/16


mysql_primary: "{{ groups['db_servers'][0] }}"
mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_primary) | first | default(mysql_primary) }}" 

mysql_host: "{{ hostvars[groups['db_servers'][0]]['ansible_default_ipv4']['address'] }}"
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636264386265636639316537333262373463306636393330376638623037656264306466306263
          3331613061653435363639353138313037636334623361330a313738323830333265643837643730
          37386231666234393636333965633166626236663164383034346232343864303764396466316263
          3963336565613763610a616462613033656666653233363538643937613532353630346231343731
          3935



mydomain: batice.ttu



mysql_exporter_username: exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33616563316136326661636235656135623235336634646563663361313232356237326635383938
          3333376361616561306530616161623537623533356630380a396133316136663039653138663561
          37623165613461323366343662356335653266363834656237333264376133653430306237363636
          6538633434336263350a353739623534636630343939376131383830336266333135666233393532
          30646131633931663538396663353632313661633739366538303530383262623536


grafana_user: mjeyhun
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63363135303330616634303730653561623238363438366134393565636138313338383035373638
          3365393362383264323532663735653135386330336537610a656666663235383064646562383564
          35386463306561343362303138316437323661343939323265626234623066383134613930353631
          3564636436633335610a306336363164653066656436646331313061353630303133656461653331
          3033


backup_server_ip: 192.168.42.5
backup_server_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAtnpnME3TsMyvcJyiYawMBod33jkDcFG9Pb1rlxDiXX"


backup_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62393066323736393164633635653763613764323261633663303862323463646663623436363437
          3937343766666466643033623937616139306338353761350a633466363430356464386661623432
          33633033303839613438356662376331656433396361653962623238663032303638626433326134
          6234613334643361340a396261653432376165303566646230356330323733396263626363383235
          3236

replication_username: replication

replication_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61303538623439353364366464656562323162393065303531303462636137373837663935366564
          6162323264666263326238316635306562653135333737640a373862393532386631363366346263
          62373836316464353964306463656463326437386431366635613335623761646664636537306537
          6564306264666166310a346466326437656432336639643831343866633861323766623431316565
          3334

node_id: "{{ (ansible_port / 100) | int }}"

grafana_port: 3001
agama_port: 8001

agama_container_count: 2


keepalivedpass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38613166373338343564643435643631353737393631643965346132383936336562356361656161
          3531366564626661656438653466336366613334326437640a326366626564666330653530633961
          30373033363337393038373461343438303635636633396533383664336531663539623539303836
          3961396664323663650a633364303439326437383436646164363130623763616565646665366164
          6131
