- name: install nginx
  apt:
    name: nginx
    state: present

- name: Apply Nginx configuration using template
  template: 
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install Nginx exporter
  apt:
    name: prometheus-nginx-exporter
    state: present

- name: Ensure nginx exporter started
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true 
