- name: Install HAProxy and HAProxy Exporter
  apt:
    name: 
      - haproxy
    state: present


- name: Config file for HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Haproxy started
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started

- name: Install prometheus haproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Config file for exporter
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: prometheus-haproxy-exporter restart

- name: Ensure haproxy-exporter is enabled and running
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true



