- name: Install HAProxy and HAProxy Exporter
  apt:
    name: 
      - haproxy
    state: present


- name: Config file for HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Haproxy started
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started

- name: Install prometheus haproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Config file for exporter
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: prometheus-haproxy-exporter restart

- name: Ensure haproxy-exporter is enabled and running
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Add CNAME records for haproxy
  nsupdate:
    key_name: "{{ update_key_name }}"
    key_algorithm: "{{ update_key_algorithm }}"
    key_secret: "{{ dns_update_key }}"
    server: "localhost"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ haproxy_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_primary'][0]Â }}"

