- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/grafana
    - /opt/grafana/provisioning
    - /opt/grafana/provisioning/dashboards
    - /opt/grafana/provisioning/datasources

- name: Create Grafana configuration file from template securely
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    owner: 472
    group: 0
    mode: "0400"
  no_log: true
  notify:
    - Restart Grafana container

- name: Grafana Docker container
  community.docker.docker_container:
    image: grafana/grafana
    name: grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    restart_policy: "always"

- name: Create Grafana dashboard file
  ansible.builtin.template:
    src: dashboards.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify:
    - Restart Grafana container

- name: Create Grafana datasource provisioning file
  ansible.builtin.template:
    dest: /opt/grafana/provisioning/datasources/default.yaml
    src: datasources.yaml.j2
  notify:
    - Restart Grafana container

- name: Upload main.json to the server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  notify: Restart Grafana container
  loop:
    - main.json
    - backups.json
    - agama_logs.json
    - mysql.json
