- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: present

- name: Template "agama.ini.j2" file
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify:
    - Restart uWSGI

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
