- name: Initial setup
  apt:
    cache_valid_time: 86400

- name: Create agama user
  ansible.builtin.user:
    user: agama
    state: present
    shell: /bin/bash

- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    group: agama
    mode: '0755'

- name: Install agama.py dependencies
  apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql
    state: present

- name: Install agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/main/agama.py
    dest: /opt/agama/agama.py


