- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL service is started and enabled
  service: 
    name: mysql
    state: started
    enabled: yes

- name: MySQL override.cnf
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Install Python MySQL library
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL User
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Cnf files for exporter
  template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.j2
    owner: prometheus
    mode: '0600'
  no_log: true
  notify: Restart mysqld-exporter

- name: MySQL exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Configure mysqld_exporter systemd service to use .my.cnf
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-mysqld-exporter
    regexp: '^ARGS='
    line: 'ARGS="--config.my-cnf=/var/lib/prometheus/.my.cnf"'
  notify: Restart mysqld-exporter

- name: Create MySQL user for the exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_username }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Ensure Prometheus MySQL Exporter is started and enabled
  systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

 

