- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL service is started and enabled
  service: 
    name: mysql
    state: started
    enabled: yes

- name: MySQL override.cnf
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Install Python MySQL library
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: MySQL User
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true



- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present
    policy_rc_d: 101


- name: Cnf files for exporter
  template:
    dest: /var/lib/prometheus/.my.cnf
    src: my.cnf.j2
    owner: prometheus
    mode: '0600'
  no_log: true
  notify: Restart mysqld-exporter

- name: Create MySQL user for the exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_username }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT"
    host: "localhost"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    column_case_sensitive: false
  no_log: true
  notify: Restart mysqld-exporter

- name: Configure mysqld_exporter systemd service to use .my.cnf
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-mysqld-exporter
    regexp: '^ARGS='
    line: 'ARGS="--config.my-cnf=/var/lib/prometheus/.my.cnf"'
  notify: Restart mysqld-exporter

- name: Ensure Prometheus MySQL Exporter is started and enabled
  systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true


- name: Ensure MySQL backup directory exists
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: "0750"


- name: Create backup MySQL user and grant privileges
  ansible.builtin.mysql_user:
    name: backup
    host: localhost
    password: "{{ backup_mysql_password }}"
    priv: "agama.*:SELECT,LOCK TABLES"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true


- name: Create .my.cnf for backup user
  ansible.builtin.template:
    src: "backup_my.cnf.j2"
    dest: "/home/backup/.my.cnf"
    owner: backup
    group: backup
    mode: '0600'
  no_log: true

- name: Ensure /etc/cron.d/mysql-backup is created
  ansible.builtin.template:
    src: backup-cron.j2
    dest: /etc/cron.d/mysql-backup
    owner: root
    group: root
    mode: '0644'
  notify: restart cron

- name: start cron
  service:
    name: cron
    state: started
    enabled: true

- name: Create replication user with REPLICATION SLAVE permissions
  community.mysql.mysql_user:
    name: "{{ replication_username }}"
    password: "{{ replication_user_password }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  no_log: true

- name: Set MySQL read_only mode dynamically
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_primary else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: Add CNAME records for mysql
  nsupdate:
    key_name: "{{ update_key_name }}"
    key_algorithm: "{{ update_key_algorithm }}"
    key_secret: "{{ dns_update_key }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"    
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ db_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_primary'][0]Â }}"
