- name: Install Loki
  apt:
    name: loki
    state: present
    update_cache: yes


- name: Create Loki data directory
  file:
    path: /var/lib/loki
    state: directory
    owner: loki
    mode: "0755"

- name: Configure Loki
  template:
    src: config.yml.j2
    dest: /etc/loki/config.yml
    owner: loki
    mode: "0644"
  notify: Restart Loki

- name: Enable and start Loki
  systemd:
    name: loki
    enabled: true
    state: started

- name: Ensure Loki backup directory exists
  file:
    path: /home/backup/loki
    state: directory
    owner: backup
    group: backup
    mode: "0750"

- name: Install Loki backup cron
  template:
    src: backup-cron.j2
    dest: /etc/cron.d/loki-backup
    owner: root
    group: root
    mode: 0644
  notify: restart cron

- name: start cron
  service:
    name: cron
    state: started
    enabled: true

- name: Add CNAME records for Loki
  nsupdate:
    key_name: "{{ update_key_name }}"
    key_algorithm: "{{ update_key_algorithm }}"
    key_secret: "{{ dns_update_key }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ loki_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_primary'][0]Â }}" 
