- name: install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Ensure Prometheus service is enabled and started
  service:
    name: prometheus
    state: started
    enabled: true

- name: Apply Prometheus default configuration from template
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart Prometheus

- name: Update Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2  
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Install Prometheus backup cron
  template:
    src: backup-cron.j2
    dest: /etc/cron.d/prometheus-backup
    owner: root
    group: root
    mode: 0644
  notify: restart cron

- name: start cron
  service:
    name: cron
    state: started
    enabled: true


- name: Add CNAME records for prometheus
  nsupdate:
    key_name: "{{ update_key_name }}"
    key_algorithm: "{{ update_key_algorithm }}"
    key_secret: "{{ dns_update_key }}"
    server: "127.0.0.1"
    zone: "{{ mydomain }}."
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ prometheus_records | dict2items }}"
  run_once: True
  no_log: true
  notify: reload rndc
  delegate_to: "{{ groups['dns_primary'][0]Â }}"
