#- name: Ansible ping module
  #  ansible.builtin.ping:

# - name: add user juri
#  ansible.builtin.user:
#    user: juri
#    state: present
#    shell: /bin/bash

# - name: add juri authorized key
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: add user roman
#  ansible.builtin.user:
#    user: roman
#    state: present
#    shell: /bin/bash

#- name: add roman authorized key
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install Prometheus Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Prometheus Node Exporter is started and enabled
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
    keyring: /etc/apt/keyrings/grafana.gpg

- name: Add grafana repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Ensure the "backup" user exists and SSH key pair is generated
  ansible.builtin.user:
    name: backup
    home: /home/backup
    state: present
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: Add backup server SSH key to known_hosts for user backup
  ansible.builtin.template:
    src: "known_hosts.j2"
    dest: "/home/backup/.ssh/known_hosts"
    owner: backup
    group: backup
    mode: '0644'
